spring.application.name: shoprabbit
spring.datasource.url: jdbc:postgresql://localhost:5432/shop_rabbit
spring.datasource.username: ${DB_USERNAME}
spring.datasource.password: ${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto: update
